# Copyright (c) 2024, Victor Chavez (vchavezb@protonmail.com)
# SPDX-License-Identifier: Apache-2.0

name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.13
    runs-on: ubuntu-22.04
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
      BOARD: cannext
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialize
        run: |
          west init -l .
          west update -o=--depth=1 -n
          ls
      - name: Run tests
        run: |
          ./zephyr/scripts/twister -vvv -T ./

